name: "Build and Package"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      lambda_name:
        required: true
        type: string
      changed:
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Cache Go modules
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        working-directory: lambdas/${{ inputs.lambda_name }}
        run: go mod download

      - name: Ensure dependencies are downloaded
        working-directory: ./lambdas/${{ inputs.lambda_name }}
        run: go mod tidy

      - name: Ensure environment folder exists
        run: |
          mkdir -p environments/${{ inputs.environment }}
          ls environments

      - name: Build or generate dummy zip
        shell: bash
        run: |
          ZIP_PATH="environments/${{ inputs.environment }}/${{ inputs.lambda_name }}.zip"
          MODULE_DIR="lambdas/${{ inputs.lambda_name }}"

          if [ "${{ inputs.changed }}" = "true" ]; then
            echo "✅ Changes detected → building ${{ inputs.lambda_name }}"

            cd "$MODULE_DIR"

            # Build from module root
            CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
              -tags lambda.norpc \
              -trimpath \
              -ldflags "-s -w" \
              -buildvcs=false \
              -o bootstrap \
              ./src/cmd

            # mkdir -p "environments/${{ inputs.environment }}"
            # zip -X -r "../environments/${{ inputs.environment }}/${{ inputs.lambda_name }}.zip" bootstrap
            zip -X -r "${{ inputs.lambda_name }}.zip" bootstrap

            ls 
            cp "${{ inputs.lambda_name }}.zip" "$ZIP_PATH"
            
            pwd
            ls
            rm -f bootstrap
            ls
            cd ..
            pwd
            ls
          else
            echo "ℹ️ No changes detected → creating deterministic dummy zip"

            mkdir -p "environments/${{ inputs.environment }}"
            mkdir -p dummy-lambda
            touch dummy-lambda/bootstrap
            zip -X -r "$ZIP_PATH" dummy-lambda/bootstrap
            rm -rf dummy-lambda
          fi


      - name: Upload Lambda artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.lambda_name }}-${{ inputs.environment }}
          path: environments/${{ inputs.environment }}/${{ inputs.lambda_name }}.zip
