name: "Build and Package"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      lambda_name:
        required: true
        type: string
      changed:
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        working-directory: ./lambdas/${{ inputs.lambda_name }}
        run: go mod download

      - name: Ensure dependencies are downloaded
        working-directory: ./lambdas/${{ inputs.lambda_name }}
        run: go mod tidy
            
      - name: Ensure environment folder exists
        run: mkdir -p environments/${{ inputs.environment }}

      - name: Build or generate dummy zip
        run: |
          # ZIP_PATH=environments/${{ inputs.environment }}/${{ inputs.lambda_name }}.zip
          # if [ "${{ inputs.changed }}" == "true" ]; then
          #   echo "Changes detected → building ${{ inputs.lambda_name }}"
          #   cd lambdas/${{ inputs.lambda_name }}/src/cmd
          #   CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -tags lambda.norpc -trimpath -ldflags "-s -w" -buildvcs=false -o bootstrap
          #   zip -r -X $ZIP_PATH bootstrap
          #   cd -
          # # else
          # #   echo "No changes detected → creating deterministic dummy zip for ${{ inputs.lambda_name }}"
          # #   echo "dummy" > dummy.txt
          # #   zip -r -X $ZIP_PATH dummy.txt
          # #   rm dummy.txt
          # # fi
          # else
          #   echo "No changes detected → creating deterministic dummy zip for ${{ inputs.lambda_name }}"
          #   # Create an empty bootstrap file inside zip
          #   mkdir -p dummy-lambda
          #   touch dummy-lambda/bootstrap
          #   zip -r -X $ZIP_PATH dummy-lambda/*
          #   rm -rf dummy-lambda
          # fi         

          ZIP_PATH=environments/main/${{ inputs.lambda_name }}.zip

          ls
          
          if [ "${{ inputs.changed }}" == "true" ]; then
            echo "Changes detected → building ${{ inputs.lambda_name }}"

            cd lambdas/${{ inputs.lambda_name }}/src/cmd

            CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
              -tags lambda.norpc \
              -trimpath \
              -ldflags "-s -w" \
              -buildvcs=false \
              -o bootstrap

            zip -r -X ../../$ZIP_PATH bootstrap
            cd -
          else
            echo "No changes detected → creating deterministic dummy zip"

            mkdir -p dummy-lambda
            touch dummy-lambda/bootstrap
            zip -r -X $ZIP_PATH dummy-lambda/*
            rm -rf dummy-lambda
          fi

      - name: Upload Lambda artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.lambda_name }}-${{ inputs.environment }}
          path: environments/${{ inputs.environment }}/${{ inputs.lambda_name }}.zip
